### PR TITLE
Added debounce function, button bounce fixed

### PR DESCRIPTION
**Pull request by jesstr**
Seems that button debounce with tmr.delay() doesn't work actually, so added debounce function with local systick which works more stable

### CODE REVIEW

**Comment by jesstr** [comment]
Merged some features: 
1) Multi-SSID configuration support: Several SSIDs can be configured to connect to. Chip will connect to the first found SSID.
2) Added telnet server from https://github.com/jesstr/luatool: Added OTA by telnet support with luatool.lua script.

**Review by elric91 — APPROVED** [review]

**Review by elric91 — APPROVED** [review]
Have to make it optionnal (through config) later to avoid unexpected security holes

**Comment by elric91** [comment]
Thanks again !
Will have a  deeper look later in the "broker / ota reconnect" commit as I don't yet get what behavior it is supposed to mitigate

**Comment by jesstr** [comment]
Hi! You can reproduce broker/ota reconnect issue if you run some script that creates a tcp connection,  (e.g ota.lua), and than rerun it (for example you have uploaded the code, made some changes in it and then uploaded it again). 

You will get something like this:
> dofile("ota.lua")
Server running...
> dofile("ota.lua");
ota.lua:41: address in use
stack traceback:
	[C]: in function 'listen'
	ota.lua:41: in main chunk
	[C]: in function 'dofile'
	stdin:1: in main chunk

After my short fix server just reconnects:
> dofile("ota.lua")
Server running...
> dofile("ota.lua")
Server running...

The same with broker.lua., but it loops in infinite connection attempts.

**Pull request merged**
